### PR TITLE
add race time column

### PR DESCRIPTION
**Pull request by valgit**
Add a race time column in the display of fleet.
Useful to create some ranking for team and so on.

### CODE REVIEW

**Comment by mcmgj** [comment]
why complicate life when the column exists?

**Comment by valgit** [comment]
@mcmgj what column did you speak of ? I did'nt see any such column like "race time" ?

**Comment by mcmgj** [comment]
HI, 
may be you or i, haven't the same Fleet display; The second column is the date/time of the record where you can get VR rank of skipper, all of these info are right only if you click on the boat if the boat are not on your friend / team list.
I have make many ranking for many group of skipper s on many past years. On record's races you have also 2 more column for help the "ranker"

**Comment by valgit** [comment]
hi,
yes @mcmgj , I see what you mean, but : 
* as you said, o have ranking you need to click on each skipper
* you have no time info, just ranking, this column add the race time info for the race (not in case of record, only standard race), so you can have delta time of each skipper

**Comment by mcmgj** [comment]
False : the time on column Date/time is the second when you click on boat, may be you haven't see this before, 
[vor_6_pdd_20.zip](https://github.com/mak08/VRDashboard/files/7663265/vor_6_pdd_20.zip)

sample

**Comment by valgit** [comment]
what did you mean by that ?
only have : 

RT | Skipper | Last Update | Rank | DTF | DTU | BRG | Sail | State | Position | HDG | TWA | TWS | Speed | Factor | Foils | Options

no date/time here ?
how did you build your xls file ?

**Comment by mcmgj** [comment]
Last Update is a timestamp  date/time

**Comment by valgit** [comment]
@mcmgj I've take a look at the last update. On the last TJV imoca i got this :
	`xxxx	11:20:16 UTC	12236	(0.0)	0.0	-°	LJ (Auto)	arrived	14°36'33.08"N 61°01'04.62"W	24.000	57.562	17.4	-`
and yes 11:20:16 is the hour for finish, but no date !, so how did you get the date ?

**Comment by mcmgj** [comment]
Hi 
The date format received is : **"date":1.519166118741E12** so you can know date and hour, only hour is displayed

**Comment by mcmgj** [comment]
to have full date format only change in 
function makeFriendListLine(uid)

in the line : 

+ '<td class="time">' + formatTime(r.lastCalcDate) + '</td>'

replace formatTime by formatDateUTC


but only for you because the screen width is not expandable

**Comment by mak08** [comment]
I'm sorry, but I won't pull this. The UI is really crowded already, and as far as I can see the information you're looking for basically is available already by means of the start time. For normal races, start time is the race start time and is the same for all boats. For record races, each individual start time is displayed in column Start Date. If the elapsed time is needed in an external tool, it should be computed by the external tool.

**Pull request closed without merging**
