### PR TITLE
Modifications

### PR DESCRIPTION
**Pull request by GeGaX**
- Add thead/tbody on makeFriendsHTML(rf), makeTableHTML (r).
- Remove stealthMode.
- Move style="width: 100%" in style.css

### CODE REVIEW

**Comment by mak08** [comment]
Thanks for spotting the obsolete stealthMode. 
Can you please remove the other changes?
- I'd rather keep the style in css and remove it from the HTML tag instead.
- The 'sticky' property must not be removed, I think.

**Comment by GeGaX** [comment]
* I'd rather keep the style in css and remove it from the HTML tag instead.
--> Can you develop please?
are you talking about table style = "width: 100%" ?

* The 'sticky' must not be removed, I think
--> you prefer to keep thead class = "sticky" ?

**Comment by mak08** [comment]
Yes & Yes

**Comment by GeGaX** [comment]
I made the changes, I test a little and if everything is ok I send a pull request.

**Comment by mak08** [comment]
Hmm, look at Files changed. There are now changed file modes and an additional file. Also the thead/sticky stuff is working already, no need to change it.

Don't worry, I'll pull your changes manually.

**Pull request closed without merging**
